title: scRNA-seq of opossum embryo organogenesis
initial_feature: IGFBP2
tracker: trackers/google-analytics.test.html
datasets:
  Integrated:
    Opossum:
      file: data/opossum.h5
    E10.5:
      file: data/E105.h5
  Replicates:
    E8.5:
      file: data/E85_all.h5
    E9.5:
      file: data/E95_all.h5
    E10.5 anterior:
      file: data/E105_anterior.h5
    E10.5 posterior:
      file: data/E105_posterior.h5
