title: Single cell transcriptome atlases of the developing mouse and human spinal cord
initial_feature: SOX2
datasets:
  Human:
    config:
      initial_feature: SOX2
    All cells:
      file: data/human.h5
    CNS:
      file: data/human_neural.h5
    CNS progenitors:
      config:
        initial_feature: OLIG2
      file: data/human_progenitor.h5
    CNS neurons:
      file: data/human_neuron.h5
    PNS:
      file: data/human_peripheral.h5
  Mouse:
    config:
      initial_feature: Sox2
    All cells:
      file: data/mouse.h5
    CNS:
      file: data/mouse_neural.h5
    CNS progenitors:
      config:
        initial_feature: Olig2
      file: data/mouse_progenitor.h5
    CNS neurons:
      file: data/mouse_neuron.h5
    PNS:
      file: data/mouse_peripheral.h5
