title: An informative project title to go in the header
initial_feature: a feature in the matrix to initialise with
datasets:
  dropdown group 1:
    dataset 1:
      file: /path/to/a/trimmed/dataset.h5
    dataset 2:
      file: relative/path/to/a/trimmed/dataset.h5
  dropdown group 2:
    dataset 1:
      file: /path/to/another/trimmed/dataset.h5
