title: An informative project title to go in the header
initial_feature: a feature in the matrix
tracker: trackers/untracked.html
datasets:
  dropdown group 1:
    config:
      initial_feature: a feature that 'dropdown group 1' can be initialised with
    dataset 1:
      file: /path/to/a/trimmed/dataset.h5
    dataset 2:
      config:
        initial_feature: a feature that 'dataset 2' of 'dropdown group 1' can be initialised with
      file: relative/path/to/a/trimmed/dataset.h5
  dropdown group 2:
    dataset 1:
      file: /path/to/another/trimmed/dataset.h5
